//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CADA.Portal.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class CADA_PortalEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“CADA_PortalEntities”部分中的连接字符串初始化新 CADA_PortalEntities 对象。
        /// </summary>
        public CADA_PortalEntities() : base("name=CADA_PortalEntities", "CADA_PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CADA_PortalEntities 对象。
        /// </summary>
        public CADA_PortalEntities(string connectionString) : base(connectionString, "CADA_PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CADA_PortalEntities 对象。
        /// </summary>
        public CADA_PortalEntities(EntityConnection connection) : base(connection, "CADA_PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<HomePage_Message> HomePage_Message
        {
            get
            {
                if ((_HomePage_Message == null))
                {
                    _HomePage_Message = base.CreateObjectSet<HomePage_Message>("HomePage_Message");
                }
                return _HomePage_Message;
            }
        }
        private ObjectSet<HomePage_Message> _HomePage_Message;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<HomePage_Message_Log> HomePage_Message_Log
        {
            get
            {
                if ((_HomePage_Message_Log == null))
                {
                    _HomePage_Message_Log = base.CreateObjectSet<HomePage_Message_Log>("HomePage_Message_Log");
                }
                return _HomePage_Message_Log;
            }
        }
        private ObjectSet<HomePage_Message_Log> _HomePage_Message_Log;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<YearReportMain> YearReportMain
        {
            get
            {
                if ((_YearReportMain == null))
                {
                    _YearReportMain = base.CreateObjectSet<YearReportMain>("YearReportMain");
                }
                return _YearReportMain;
            }
        }
        private ObjectSet<YearReportMain> _YearReportMain;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<YearReportPhoto> YearReportPhoto
        {
            get
            {
                if ((_YearReportPhoto == null))
                {
                    _YearReportPhoto = base.CreateObjectSet<YearReportPhoto>("YearReportPhoto");
                }
                return _YearReportPhoto;
            }
        }
        private ObjectSet<YearReportPhoto> _YearReportPhoto;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 HomePage_Message EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToHomePage_Message(HomePage_Message homePage_Message)
        {
            base.AddObject("HomePage_Message", homePage_Message);
        }
    
        /// <summary>
        /// 用于向 HomePage_Message_Log EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToHomePage_Message_Log(HomePage_Message_Log homePage_Message_Log)
        {
            base.AddObject("HomePage_Message_Log", homePage_Message_Log);
        }
    
        /// <summary>
        /// 用于向 YearReportMain EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToYearReportMain(YearReportMain yearReportMain)
        {
            base.AddObject("YearReportMain", yearReportMain);
        }
    
        /// <summary>
        /// 用于向 YearReportPhoto EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToYearReportPhoto(YearReportPhoto yearReportPhoto)
        {
            base.AddObject("YearReportPhoto", yearReportPhoto);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CADA.Portal.Model", Name="HomePage_Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HomePage_Message : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 HomePage_Message 对象。
        /// </summary>
        /// <param name="sID">SID 属性的初始值。</param>
        public static HomePage_Message CreateHomePage_Message(global::System.String sID)
        {
            HomePage_Message homePage_Message = new HomePage_Message();
            homePage_Message.SID = sID;
            return homePage_Message;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                if (_SID != value)
                {
                    OnSIDChanging(value);
                    ReportPropertyChanging("SID");
                    _SID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SID");
                    OnSIDChanged();
                }
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_CN
        {
            get
            {
                return _Title_CN;
            }
            set
            {
                OnTitle_CNChanging(value);
                ReportPropertyChanging("Title_CN");
                _Title_CN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_CN");
                OnTitle_CNChanged();
            }
        }
        private global::System.String _Title_CN;
        partial void OnTitle_CNChanging(global::System.String value);
        partial void OnTitle_CNChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_EN
        {
            get
            {
                return _Title_EN;
            }
            set
            {
                OnTitle_ENChanging(value);
                ReportPropertyChanging("Title_EN");
                _Title_EN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_EN");
                OnTitle_ENChanged();
            }
        }
        private global::System.String _Title_EN;
        partial void OnTitle_ENChanging(global::System.String value);
        partial void OnTitle_ENChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_Image
        {
            get
            {
                return _Title_Image;
            }
            set
            {
                OnTitle_ImageChanging(value);
                ReportPropertyChanging("Title_Image");
                _Title_Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_Image");
                OnTitle_ImageChanged();
            }
        }
        private global::System.String _Title_Image;
        partial void OnTitle_ImageChanging(global::System.String value);
        partial void OnTitle_ImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body_Title
        {
            get
            {
                return _Body_Title;
            }
            set
            {
                OnBody_TitleChanging(value);
                ReportPropertyChanging("Body_Title");
                _Body_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body_Title");
                OnBody_TitleChanged();
            }
        }
        private global::System.String _Body_Title;
        partial void OnBody_TitleChanging(global::System.String value);
        partial void OnBody_TitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body_Message
        {
            get
            {
                return _Body_Message;
            }
            set
            {
                OnBody_MessageChanging(value);
                ReportPropertyChanging("Body_Message");
                _Body_Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body_Message");
                OnBody_MessageChanged();
            }
        }
        private global::System.String _Body_Message;
        partial void OnBody_MessageChanging(global::System.String value);
        partial void OnBody_MessageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CADA.Portal.Model", Name="HomePage_Message_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HomePage_Message_Log : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 HomePage_Message_Log 对象。
        /// </summary>
        /// <param name="sID">SID 属性的初始值。</param>
        public static HomePage_Message_Log CreateHomePage_Message_Log(global::System.String sID)
        {
            HomePage_Message_Log homePage_Message_Log = new HomePage_Message_Log();
            homePage_Message_Log.SID = sID;
            return homePage_Message_Log;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                if (_SID != value)
                {
                    OnSIDChanging(value);
                    ReportPropertyChanging("SID");
                    _SID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SID");
                    OnSIDChanged();
                }
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_CN
        {
            get
            {
                return _Title_CN;
            }
            set
            {
                OnTitle_CNChanging(value);
                ReportPropertyChanging("Title_CN");
                _Title_CN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_CN");
                OnTitle_CNChanged();
            }
        }
        private global::System.String _Title_CN;
        partial void OnTitle_CNChanging(global::System.String value);
        partial void OnTitle_CNChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_EN
        {
            get
            {
                return _Title_EN;
            }
            set
            {
                OnTitle_ENChanging(value);
                ReportPropertyChanging("Title_EN");
                _Title_EN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_EN");
                OnTitle_ENChanged();
            }
        }
        private global::System.String _Title_EN;
        partial void OnTitle_ENChanging(global::System.String value);
        partial void OnTitle_ENChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title_Image
        {
            get
            {
                return _Title_Image;
            }
            set
            {
                OnTitle_ImageChanging(value);
                ReportPropertyChanging("Title_Image");
                _Title_Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title_Image");
                OnTitle_ImageChanged();
            }
        }
        private global::System.String _Title_Image;
        partial void OnTitle_ImageChanging(global::System.String value);
        partial void OnTitle_ImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body_Title
        {
            get
            {
                return _Body_Title;
            }
            set
            {
                OnBody_TitleChanging(value);
                ReportPropertyChanging("Body_Title");
                _Body_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body_Title");
                OnBody_TitleChanged();
            }
        }
        private global::System.String _Body_Title;
        partial void OnBody_TitleChanging(global::System.String value);
        partial void OnBody_TitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body_Message
        {
            get
            {
                return _Body_Message;
            }
            set
            {
                OnBody_MessageChanging(value);
                ReportPropertyChanging("Body_Message");
                _Body_Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body_Message");
                OnBody_MessageChanged();
            }
        }
        private global::System.String _Body_Message;
        partial void OnBody_MessageChanging(global::System.String value);
        partial void OnBody_MessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDay
        {
            get
            {
                return _CreateDay;
            }
            set
            {
                OnCreateDayChanging(value);
                ReportPropertyChanging("CreateDay");
                _CreateDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDay");
                OnCreateDayChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDay;
        partial void OnCreateDayChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreateBy
        {
            get
            {
                return _CreateBy;
            }
            set
            {
                OnCreateByChanging(value);
                ReportPropertyChanging("CreateBy");
                _CreateBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreateBy");
                OnCreateByChanged();
            }
        }
        private global::System.String _CreateBy;
        partial void OnCreateByChanging(global::System.String value);
        partial void OnCreateByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreateName
        {
            get
            {
                return _CreateName;
            }
            set
            {
                OnCreateNameChanging(value);
                ReportPropertyChanging("CreateName");
                _CreateName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreateName");
                OnCreateNameChanged();
            }
        }
        private global::System.String _CreateName;
        partial void OnCreateNameChanging(global::System.String value);
        partial void OnCreateNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CADA.Portal.Model", Name="YearReportMain")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class YearReportMain : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 YearReportMain 对象。
        /// </summary>
        /// <param name="sID">SID 属性的初始值。</param>
        /// <param name="reportYear">ReportYear 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="video">Video 属性的初始值。</param>
        /// <param name="videoRemark">VideoRemark 属性的初始值。</param>
        public static YearReportMain CreateYearReportMain(global::System.String sID, global::System.Decimal reportYear, global::System.String name, global::System.String video, global::System.String videoRemark)
        {
            YearReportMain yearReportMain = new YearReportMain();
            yearReportMain.SID = sID;
            yearReportMain.ReportYear = reportYear;
            yearReportMain.Name = name;
            yearReportMain.Video = video;
            yearReportMain.VideoRemark = videoRemark;
            return yearReportMain;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                if (_SID != value)
                {
                    OnSIDChanging(value);
                    ReportPropertyChanging("SID");
                    _SID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SID");
                    OnSIDChanged();
                }
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReportYear
        {
            get
            {
                return _ReportYear;
            }
            set
            {
                OnReportYearChanging(value);
                ReportPropertyChanging("ReportYear");
                _ReportYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportYear");
                OnReportYearChanged();
            }
        }
        private global::System.Decimal _ReportYear;
        partial void OnReportYearChanging(global::System.Decimal value);
        partial void OnReportYearChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Video
        {
            get
            {
                return _Video;
            }
            set
            {
                OnVideoChanging(value);
                ReportPropertyChanging("Video");
                _Video = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Video");
                OnVideoChanged();
            }
        }
        private global::System.String _Video;
        partial void OnVideoChanging(global::System.String value);
        partial void OnVideoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VideoRemark
        {
            get
            {
                return _VideoRemark;
            }
            set
            {
                OnVideoRemarkChanging(value);
                ReportPropertyChanging("VideoRemark");
                _VideoRemark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VideoRemark");
                OnVideoRemarkChanged();
            }
        }
        private global::System.String _VideoRemark;
        partial void OnVideoRemarkChanging(global::System.String value);
        partial void OnVideoRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CADA.Portal.Model", Name="YearReportPhoto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class YearReportPhoto : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 YearReportPhoto 对象。
        /// </summary>
        /// <param name="sID">SID 属性的初始值。</param>
        /// <param name="yearReportMainSID">YearReportMainSID 属性的初始值。</param>
        public static YearReportPhoto CreateYearReportPhoto(global::System.String sID, global::System.String yearReportMainSID)
        {
            YearReportPhoto yearReportPhoto = new YearReportPhoto();
            yearReportPhoto.SID = sID;
            yearReportPhoto.YearReportMainSID = yearReportMainSID;
            return yearReportPhoto;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                if (_SID != value)
                {
                    OnSIDChanging(value);
                    ReportPropertyChanging("SID");
                    _SID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SID");
                    OnSIDChanged();
                }
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YearReportMainSID
        {
            get
            {
                return _YearReportMainSID;
            }
            set
            {
                OnYearReportMainSIDChanging(value);
                ReportPropertyChanging("YearReportMainSID");
                _YearReportMainSID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("YearReportMainSID");
                OnYearReportMainSIDChanged();
            }
        }
        private global::System.String _YearReportMainSID;
        partial void OnYearReportMainSIDChanging(global::System.String value);
        partial void OnYearReportMainSIDChanged();

        #endregion

    
    }

    #endregion

    
}
